### ISSUE TITLE
Fix npm msvs_version error in Windows system-setup guide

### ISSUE THREAD

**Issue by ProchaLu** [upleveled/system-setup#31]
## Description

After running, `choco install python visualstudio2017-workload-vctools -y` on Windows, some users are reporting an error when trying to set the `msvs_version` option in npm using the command `npm config set msvs_version 2017`. The error message says that `msvs_version` is not a valid npm option. This issue is causing problems for users who are trying to set up their Windows environment for development.
![npm error](https://user-images.githubusercontent.com/80746311/233309856-663f7558-9732-47f8-a531-0aa311c0ad80.png)

## Possible solutions:
 - Maybe a possible solution can be to use the `--global` flag with the npm config set command to set the `msvs_version` option globally. This can be done using the following command: `npm config set msvs_version 2017 --global`
 - Maybe users can set the `msvs_version` option manually in their `npmrc` file located at `C:\Users\<username>\.npmrc` by adding the following line: `msvs_version=2017`

**Comment by karlhorky** [comment]
> From this post [stackoverflow.com/questions/75647270/node-gyp-msvs-version-is-not-a-valid-npm-option](https://stackoverflow.com/questions/75647270/node-gyp-msvs-version-is-not-a-valid-npm-option) I reached this page [nodejs/node-gyp@c7927e2](https://github.com/nodejs/node-gyp/commit/c7927e228dfde059c93e08c26b54dd8026144583).

This seems like a great tip, that in https://github.com/nodejs/node-gyp/pull/2822 (the PR associated with the commit you found), the `node-gyp` team has actually removed this instruction from their readme:

![Screenshot 2023-08-23 at 12 55 07](https://github.com/upleveled/system-setup/assets/1935696/91fea792-0d5a-4503-bb61-a8f0bbab5e07)

But this alone is not enough information for us to remove it from our instructions, because the PR also notes:

> @gengjiawen in [comment 1161506873](https://github.com/nodejs/node-gyp/pull/2822#discussion_r1161506873): Can you delete this line ? I think for most user, this is not necessary.

So if it is necessary for some users, then we want to make sure that those users do not have problems.

I've asked @gengjiawen (a Node.js team member) for more details about that here:

- https://github.com/nodejs/node-gyp/pull/2822#issuecomment-1689756904

If we can find out which users will be affected by this, then we can edit our System Setup instructions for Windows to avoid this problem.

**Comment by karlhorky** [comment]
> Another post [davy.ai/node-gyp-msvs_version-is-not-a-valid-npm-option](https://davy.ai/node-gyp-msvs_version-is-not-a-valid-npm-option/) suggested another way `node-gyp configure --msvs_version=2017 `.

Indeed the `node-gyp configure --msvs_version=...` format of the configuration option also seems to be valid, as is documented in [the `node-gyp` readme](https://github.com/nodejs/node-gyp#:~:text=node%2Dgyp%20configure%20%2D%2Dmsvs_version%3D2015), so this may also be a path forward (if we decide we want to keep the configuration in the System Setup guide).

**Comment by karlhorky** [comment]
@ProchaLu an additional idea here would be to add a step to the Windows System Setup guide which would cause the Visual Studio C++ build tools to be used (some project that would trigger compiling native code), and if it's not working, then to add additional possible debugging steps.

**Comment by gengjiawen** [comment]
@ProchaLu Install visual studio 2022 is enough, everything just works. 
`npm config set msvs_version` is unnecessary.

**Comment by karlhorky** [comment]
Thanks for the tip @gengjiawen ! 

@ProchaLu maybe you can try the following changes and test on a fresh machine:

- switch [`visualstudio2017-workload-vctools`](https://community.chocolatey.org/packages/visualstudio2017-workload-vctools) to [`visualstudio2022-workload-vctools`](https://community.chocolatey.org/packages/visualstudio2022-workload-vctools) 
- remove the `npm config set msvs_version ...` command

Maybe @Eprince-hub will have to help with the fresh Windows machine.

**Comment by Davidihl** [comment]
@ProchaLu installing `visualstudio2022-workload-vctools` will install `visualstudio2022buildtools` in the process, so it may not be necessary to install it as a prerequisite 
![image](https://github.com/upleveled/system-setup/assets/111972510/1ac56b09-b948-44af-9bed-d403594cf8c9)
