### ISSUE TITLE
Setup for Linux: Curl should be installed before first command

### ISSUE THREAD

**Issue by CornaSn** [upleveled/system-setup#55]
In Ubunutu curl is not installed. Must be installed before you can use first command.

[https://github.com/upleveled/system-setup/blob/main/linux.md](https://github.com/upleveled/system-setup/blob/main/linux.md)

**Comment by karlhorky** [comment]
Thanks for the report!

@ProchaLu @Eprince-hub looks like we'll need a new command at the beginning of the Linux System setup guide `sudo apt-get install -y curl`

2nd PR: Although it seems like in modern resources, `apt-get` has changed to `apt` eg. `sudo apt install -y curl`

- https://www.cyberciti.biz/faq/how-to-install-curl-command-on-a-ubuntu-linux/
- https://serverfault.com/questions/1153864/can-i-rely-on-curl-being-installed-on-debian-ubuntu-how-could-i-find-out
