### ISSUE TITLE
ERR_PNPM_NO_GLOBAL_BIN_DIR when installing Preflight on Ubuntu

### ISSUE THREAD

**Issue by CornaSn** [upleveled/system-setup#58]
[https://github.com/upleveled/system-setup/blob/main/linux.md](https://github.com/upleveled/system-setup/blob/main/linux.md) - step 14

Copied this step:
```
sudo pnpm add --global @upleveled/preflight
```
Received this error: 
```
$ sudo pnpm add --global @upleveled/preflight
[sudo] Passwort für corna: 
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
```

The command `pnpm setup`also doesn't solve the problem

**Comment by karlhorky** [comment]
@CornaSn thanks for the report!

Could you paste the output that you received from `pnpm setup`? (you may need to run `pnpm setup` with `sudo` in front of it)

**Comment by CornaSn** [comment]
Actually I thought it's working, but unfortunately the same message still occurs and I'm unable to find a solution.

**Comment by CornaSn** [comment]
so here is what i tried

`$ sudo pnpm add --global @upleveled/preflight`
 
```
ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
```

`$ pnpm setup`
```
No changes to the environment were made. Everything is already up to date.
```

`$ sudo pnpm setup`
```
No changes to the environment were made. Everything is already up to date.
```

'$ preflight'
```
preflight: Befehl nicht gefunden.
```


Also I don't know, why some messages are in english and others are in german.

**Comment by ProchaLu** [comment]
@CornaSn tested the `sudo pnpm add --global @upleveled/preflight` without `sudo` and it worked. 

The correct command is `pnpm add --global @upleveled/preflight`
