### ISSUE TITLE
Error when starting Docker Desktop after new installation

### ISSUE THREAD

**Issue by Eprince-hub** [upleveled/system-setup#62]
I am following the system setup for a Windows computer, and after installing Docker Desktop, following the point `20 Option A`.
I get the error below when I start the Docker Desktop

```
Hardware assisted virtualization and data execution protection must be enabled in the BIOS
```

What I have tried so far
[Step-By-Step: Enabling Hyper-V for Use on Windows 11](https://techcommunity.microsoft.com/t5/educator-developer-blog/step-by-step-enabling-hyper-v-for-use-on-windows-11/ba-p/3745905)
Following the above instruction to turn on Hyper-V on my system

I am using Windows 11 Pro

**Comment by Eprince-hub** [comment]
What worked was enabling the `virtualization` on my system BIOS following this instruction below

[Enable virtualization on Windows 11 PCs](https://support.microsoft.com/en-us/windows/enable-virtualization-on-windows-11-pcs-c5578302-6e43-4b4b-a449-8ced115f58e1)

Closing this issus

**Comment by karlhorky** [comment]
@Eprince-hub there's a PR open about this - maybe you can finish this PR and get it merged:

- #16 

I'll assign you

**Comment by karlhorky** [comment]
Reopening until #16 is finished
